### ISSUE TITLE
Unpredictable crashing due to null pointer exception

### ISSUE THREAD

**Issue by rhayes777** [gitdoapp/SugarRecord#136]
I experience null pointer exceptions, seemingly at random. The one I'm currently getting occurs when I call SugarRecord.findAll(<class>).

Here's my stacktrace:

java.lang.NullPointerException
at com.orm.SugarRecord.findAsIterator(SugarRecord.java:166)
at com.orm.SugarRecord.findAll(SugarRecord.java:146)
at connectivity.TestStewardship.loadUsers(TestStewardship.java:55)
at connectivity.TestStewardship.testStewardship(TestStewardship.java:40)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at junit.framework.TestCase.runTest(TestCase.java:168)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at junit.framework.TestResult.runProtected(TestResult.java:133)
at junit.framework.TestResult.run(TestResult.java:118)
at junit.framework.TestCase.run(TestCase.java:124)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:177)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1619)

I have defined:
<meta-data
            android:name="DOMAIN_PACKAGE_NAME"
            android:value="model.data" />
android:name="com.orm.SugarApp"

In both my main and test manifests.

What's really strange about this is that it is so inconsistent. I can run a test several times successfully and then have it not work again without having changed anything about my code. 

I'd really like to use sugar a lot more but I'm worried about how unpredictable it seems!

Thanks

**Comment by dchavezlive** [comment]
This is not a Java library. It seems you are using it in an Android environment. It will not work.
